---

name: Dependencies

"on":
  pull_request:
    branches:
      - develop

jobs:
  update-dependencies:
    name: Update requirements file
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Generate updated requirements.txt
        run: poetry export -f requirements.txt --output requirements.txt

      - name: Commit and add changes
        run: git commit -m "fix: Updating requirements.txt from Poetry"

      - name: Fetch from develop
        run: git fetch origin develop

      - name: Push to develop
        run: git push origin HEAD:develop